services:
  postgres:
    image: postgres:15-alpine
    container_name: bidly-db
    restart: always
    environment:
      POSTGRES_DB: bidly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bidly-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=bidly
      - DB_USERNAME=postgres
      - DB_PASSWORD=securepassword
    depends_on:
      - postgres

volumes:
  postgres_data: